version: "3.8"

services:
  postgres:
    image: postgres
    container_name: chat
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: chat
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
